language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t khoinguyen132/learning-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true khoinguyen132/learning-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "learning-docker"
  env: "Learningdocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-565899399462"
  bucket_path: "learning-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"