language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t khoinguyen132/learning-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true khoinguyen132/learning-docker npm run test